AAPL = {
    'zip': '95014', 'sector': 'Technology', 'fullTimeEmployees': 154000, 
    'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. It also sells various related services. \
        In addition, the company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; AirPods Max, an over-ear wireless headphone; and \
        wearables, home, and accessories comprising AirPods, Apple TV, Apple Watch, Beats products, HomePod, and iPod touch. Further, it provides AppleCare support services; cloud services store \
        services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts. \
        Additionally, the company offers various services, such as Apple Arcade, a game subscription service; Apple Music, which offers users a curated listening experience with on-demand radio stations; \
        Apple News+, a subscription news and magazine service; Apple TV+, which offers exclusive original content; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, \
        as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. \
        It distributes third-party applications for its products through the App Store. The company also sells its \
        products through its retail and online stores, and direct sales force; and third-party cellular network carriers, wholesalers, retailers, and resellers. \
        Apple Inc. was incorporated in 1977 and is headquartered in Cupertino, California.', 
    'city': 'Cupertino', 'phone': '408 996 1010', 'state': 'CA', 'country': 'United States', 'companyOfficers': [], 'website': 'https://www.apple.com', 
    'maxAge': 1, 'address1': 'One Apple Park Way', 'industry': 'Consumer Electronics', 'ebitdaMargins': 0.33842, 'profitMargins': 0.26407, 'grossMargins': 0.43322, 
    'operatingCashflow': 116425998336, 'revenueGrowth': 0.086, 'operatingMargins': 0.30926, 'ebitda': 130633998336, 'targetLowPrice': 157, 'recommendationKey': 'buy', 
    'grossProfits': 152836000000, 'freeCashflow': 84384628736, 'targetMedianPrice': 191, 'currentPrice': 138.25, 'earningsGrowth': 0.086, 'currentRatio': 0.927, 
    'returnOnAssets': 0.21695, 'numberOfAnalystOpinions': 43, 'targetMeanPrice': 190.2, 'debtToEquity': 178.016, 'returnOnEquity': 1.49271, 'targetHighPrice': 215, 
    'totalCash': 51511001088, 'totalDebt': 119980998656, 'totalRevenue': 386017001472, 'totalCashPerShare': 3.183, 'financialCurrency': 'USD', 'revenuePerShare': 23.471,
    'quickRatio': 0.76, 'recommendationMean': 1.9, 'exchange': 'NMS', 'shortName': 'Apple Inc.', 'longName': 'Apple Inc.', 'exchangeTimezoneName': 'America/New_York', 
    'exchangeTimezoneShortName': 'EDT', 'isEsgPopulated': False, 'gmtOffSetMilliseconds': '-14400000', 'quoteType': 'EQUITY', 'symbol': 'AAPL', 'messageBoardId': 'finmb_24937', 
    'market': 'us_market', 'annualHoldingsTurnover': None, 'enterpriseToRevenue': 6.435, 'beta3Year': None, 'enterpriseToEbitda': 19.015, '52WeekChange': 0.10611892, 
    'morningStarRiskRating': None, 'forwardEps': 6.56, 'revenueQuarterlyGrowth': None, 'sharesOutstanding': 16185199616, 'fundInceptionDate': None, 'annualReportExpenseRatio': None, 
    'totalAssets': None, 'bookValue': 4.158, 'sharesShort': 103977276, 'sharesPercentSharesOut': 0.0064, 'fundFamily': None, 'lastFiscalYearEnd': 1632528000, 
    'heldPercentInstitutions': 0.59593, 'netIncomeToCommon': 101934997504, 'trailingEps': 6.137, 'lastDividendValue': 0.23, 'SandP52WeekChange': -0.05660814, 
    'priceToBook': 33.249157, 'heldPercentInsiders': 0.00072999997, 'nextFiscalYearEnd': 1695600000, 'yield': None, 'mostRecentQuarter': 1648252800, 'shortRatio': 1.21, 
    'sharesShortPreviousMonthDate': 1648684800, 'floatShares': 16168348412, 'beta': 1.194642, 'enterpriseValue': 2483946520576, 'priceHint': 2, 'threeYearAverageReturn': None, 
    'lastSplitDate': 1598832000, 'lastSplitFactor': '4:1', 'legalType': None, 'lastDividendDate': 1651795200, 'morningStarOverallRating': None, 'earningsQuarterlyGrowth': 0.058, 
    'priceToSalesTrailing12Months': 5.7966456, 'dateShortInterest': 1651190400, 'pegRatio': 2.31, 'ytdReturn': None, 'forwardPE': 21.074696, 'lastCapGain': None, 'shortPercentOfFloat': 0.0064, 
    'sharesShortPriorMonth': 101969098, 'impliedSharesOutstanding': 0, 'category': None, 'fiveYearAverageReturn': None, 'previousClose': 140.82, 'regularMarketOpen': 139.88, 
    'twoHundredDayAverage': 159.6712, 'trailingAnnualDividendYield': 0.006249112, 'payoutRatio': 0.14310001, 'volume24Hr': None, 'regularMarketDayHigh': 141.66, 'navPrice': None, 
    'averageDailyVolume10Day': 120694930, 'regularMarketPreviousClose': 140.82, 'fiftyDayAverage': 162.7702, 'trailingAnnualDividendRate': 0.88, 'open': 139.88, 'toCurrency': None, 
    'averageVolume10days': 120694930, 'expireDate': None, 'algorithm': None, 'dividendRate': 0.92, 'exDividendDate': 1651795200, 'circulatingSupply': None, 'startDate': None, 
    'regularMarketDayLow': 137.84, 'currency': 'USD', 'trailingPE': 22.527292, 'regularMarketVolume': 49671891, 'lastMarket': None, 'maxSupply': None, 'openInterest': None, 
    'marketCap': 2237603774464, 'volumeAllCurrencies': None, 'strikePrice': None, 'averageVolume': 96803493, 
    'dayLow': 137.84, 'ask': 139.17, 'askSize': 1800, 'volume': 49671891, 'fiftyTwoWeekHigh': 182.94, 
    'fromCurrency': None, 'fiveYearAvgDividendYield': 1.1, 'fiftyTwoWeekLow': 123.13, 'bid': 139.15, 
    'tradeable': False, 'dividendYield': 0.0062, 'bidSize': 800, 'dayHigh': 141.66, 'regularMarketPrice': 138.25, 
    'preMarketPrice': 139.89, 'logo_url': 'https://logo.clearbit.com/apple.com', 'trailingPegRatio': 2.5522
}


['LIN', 'CCL', 'CUK', 'CUKPF', 'STE', 'MMM', 'AXP', 'AAPL', 'BA', 'CAT', 'CVX', 'CSCO', 'KO', 'DD', 'XOM', 'GS-PK', 'GS', 'HD', 'IBM', 'INTC', 'JNJ', 'JPM', 'MCD', 'NKE', 'MRK', 'MSFT', 'PFE', 'PG', 'TRV', 'UNH', 'VZ', 'V', 'WMT', 'WBA', 'DIS', 'ATVI', 'ADBE', 'AKAM', 'GOOGL', 'GOOG', 'AMZN', 'AAL', 'AMGN', 'ADI', 'AMAT', 'ADSK', 'ADP', 'BIIB', 'CERN', 'CHTR', 'CTXS', 'CTSH', 'CMCSA', 'COST', 'CSX', 'XRAY', 'DISCA', 'DISCK', 'DISCB', 'DISH', 'DLTR', 'EBAY', 
'EA', 'EXPE', 'FB', 'FAST', 'FISV', 'GILD', 'HSIC', 'ILMN', 'INCY', 'INTU', 'ISRG', 'KHC', 'LRCX', 'MAR', '0P0000KQL0', 'MCHP', 'MU', 'MDLZ', 'MNST', 'NTAP', 'NFLX', 'NVDA', 'NXPI', 'ORLY', 'PCAR', 'PAYX', 'PYPL', 'QCOM', 'REGN', 'ROST', 'STX', 'SWKS', 'SBUX', 'TMUS', 'TSLA', 'TXN', 'TSCO', 'ULTA', 'VRSK', 
'VRTX', 'WDC', 'XLNX', 'ABT', 'ABBV', 'ACN', 'ALL', 'MO', 'AIG', 'T', 'BAC', 'BOAPL', 'BK', 'BRK-B', 'BLK', 'BKNG', 'BMY', 'BMYMP', 'COF', 'C', 'CL', 'COP', 'CVS', 'DHR', 'DUK', 'LLY', 'EMR', 'EXC', 'FDX', 'F', 'GE', 'GM', 'HON', 'KMI', 'LOW', 'MA', 'MDT', 'MET', 'MS', 'MNSLV', 'NEE', 'OXY', 'ORCL', 'OCLCF', 'PM', 'RTX', 'SLB', 'SPG', 'SO', 'TGT', 'UNP', 'UPS', 'USB', 'WFC', 'ABMD', 'AAP', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ALK', 'ALB', 'ARE', 'ALGN', 'ALLE', 'AEE', 'AEP', 'AMT', 'AWK', 'AMP', 'ABC', 'AME', 'APH', 'ANSS', 'ANTM', 'AOS', 'AON', 'APA', 'APTV', 'ADM', 'ANET', 'AJG', 'AIZ', 'ATO', 'AZO', 'AVB', 'AVY', 'BKR', 'BLL', 'BALY', 'BAX', 'BDX', 'BBY', 'BWA', 'BXP', 'BSX', 'AVGO', 'BR', 'BF-B', 'CHRW', 'CDNS', 'CPB', 'CAH', 'KMX', 'CBRE', 'CE', 'CNC', 'CNP-PB', 'CNP', 'CF', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CFG', 'CLX', 'CME', 'CMS-PB', 'CMS', 'CMA', 'CAG', 'ED', 'STZ', 'COO', 'CPRT', 'GLW', 'CCI', 
'CMI', 'DRI', 'DVA', 'DE', 'DAL', 'DVN', 'FANG', 'DLR', 'DFS', 'DG', 'D', 'DOV', 'DHI', 'DTE', 'DRE', 'DXC', 'EMN', 'ETN', 'ECL', 'EIX', 'EW', 'ETR', 'EOG', 'EFX', 'EQIX', 'EQR', 'ESS', 'RE', 'EVRG', 'ES', 'EXPD', 'EXR', 'FFIV', 'FRT', 'FIS', 'FITB', 'FRC', 'FE', 'FLT', 'FMC', 'FTNT', 'FTV', 'FBHS', 'FOXA', 'FXBY', 'FOX', 'BEN', 'FCX', 'GPS', 'GRMN', 'IT', 'GIS', 'GPC', 'GPN', 'GWW', 'HAL', 'HBI', 'HIG', 'HAS', 'HCA', 'PEAK', 'HCP', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HRL', 'HST', 'HPQ', 'HUM', 'HBANN', 'HBAN', 'HII', 'IDXX', 'INFO', 'ITW', 'ICE', 'IFF', 'IP', 'INPAP', 'IPG', 'IVZ', 'IPGP', 'IQV', 'IRM', 'JBHT', 'JKHY', 'J', 'SJM', 'JCI', 'JNPR', 'KSU', 'K', 'KEYS', 'KMB', 'KIM-PI', 'KIM', 'KLAC', 'KR', 'LH', 'LW', 'ELAA.F', 'EL', 'LEG', 'LEN', 'LNC', 'LKQ', 
'L', 'LYB', 'MTB', 'MRO', 'MPC', 'MMC', 'MLM', 'MAS', 'MKC', 'MCK', 'MTD', 'MGM', 'MAA', 'MHK', 'MCO', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NWL', 'NEM', 'NWSA', 'NWS', 'NLSN', 'NI', 'NTRS', 'NCLH', 'NRG', 'NUE', 'OMC', 'OKE', 'PKG', 'PH', 'PNR', 'PBCT', 'PKI', 'PSX', 'PNW', 'PXD', 'PNC', 'PPG', 'PPL', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PBSTV', 'PHM', 'PVH', 'QRVO', 'PWR', 'DGX', 'RL', 'RJF', 'UHT', 'O', 'RF-PB', 'RF', 'RSG', 'RMD', 'RSMDF', 'RHI', 'ROK', 'ROL', 'ROP', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SCHW', 'SEE', 'SRE', 'SHW', 'SNA', 'LUV', 'SWK', 'STT', 'SYK', 'SIVB', 'SYF', 'SNPS', 'SYY', 'TROW', 'TTWO', 'TPR', 'TEL', 'TFX', 'TMO', 'TJX', 'TWTR', 'TSN', 'UDR', 'UAA', 'UA', 'UAL', 'URI', 'UHS', 'VFC', 'VLO', 'VTR', 'VRSN', 'VNO', 'VNORP', 'VMC', 'WAB', 'WM', 'WAT', 'WEC', 'WELL', 'WU', 'WRK', 'WY', 'WHR', 'WMB', 'WLTW', 'WTW', 'WYNN', 'XYL', 'YUM', 'ZBH', 'ZION', 'ZTS', 'CTVA', 'LNT', 'AMCR', 'AMCCF', 'BIO', 'CARR', 'CTLT', 'CDW', 'DXCM', 'DPZ', 'DPUKY', 'DOW', 'ETSY', 'GD', 'HWM', 'IEX', 'KEY', 'LHX', 'HRS', 'LVS', 'LDOS', 'LYV', 'LMT', 'LUMN', 'MKTX', 'TAP', 'TAP-A', 'NOC', 'NLOK', 'NVR', 'ODFL', 'OTIS', 'PAYC', 'PEP', 'POOL', 'PFG', 'REG', 'NOW', 'TDY', 'TER', 'TXT', 'TT', 'TDG', 'TFC', 'TYL', 'VIACA', 'VIAC', 'VTRS', 'WRB', 'WST', 'XEL', 'ZBRA', 'MTCH', 'MRNA', 'CZR', 'CRL', 'ENPH', 'GNRC', 'MPWR', 'PENN', 'PTC', 'TRMB', 'OGN', 'BBWI', 'TECH', 'BRO', 'CDAY', 'IR', 
'CTRA']